
#List of curio slot type settings
[[curiosSettings]]
	identifier = "charm"
	size = 4
	
[[curiosSettings]]
	identifier = "ring"
	size = 4

[[curiosSettings]]
	identifier = "hands"

[[curiosSettings]]
	identifier = "head"

[[curiosSettings]]
	identifier = "magnet"

[[curiosSettings]]
	identifier = "necklace"
